export type AnswerCategory = "climate" | "decision" | "explanation";

export type DecisionPageDefinition = {
  slug: string;
  keyword: string;
  title: string;
  category: AnswerCategory;
  directAnswer: string;
  audience: string;
  decisionAreas: Array<"hiring" | "product-tempo" | "capital-raising" | "burn-discipline" | "expansion-bets">;
  supportPoints: string[];
};

export const tierOneDecisionPages: DecisionPageDefinition[] = [
  {
    slug: "startup-funding-climate-this-week",
    keyword: "startup funding climate this week",
    title: "Startup Funding Climate This Week",
    category: "climate",
    directAnswer: "Funding climate is open with guardrails, not open-ended risk.",
    audience: "Founders and finance leaders deciding capital pacing.",
    decisionAreas: ["capital-raising", "burn-discipline"],
    supportPoints: ["Use climate tailwind to improve terms.", "Do not let burn outpace financing optionality."],
  },
  {
    slug: "is-it-risk-on-or-risk-off-for-startups",
    keyword: "is it risk-on or risk-off for startups",
    title: "Is It Risk-On or Risk-Off for Startups?",
    category: "climate",
    directAnswer: "Current posture is risk-on with explicit downside triggers.",
    audience: "Exec teams calibrating weekly approval velocity.",
    decisionAreas: ["product-tempo", "expansion-bets"],
    supportPoints: ["Move fast on reversible bets.", "Pause irreversible bets on threshold breaks."],
  },
  {
    slug: "startup-market-outlook",
    keyword: "startup market outlook",
    title: "Startup Market Outlook",
    category: "climate",
    directAnswer: "Near-term outlook is constructive, but stability is not guaranteed.",
    audience: "Leadership teams preparing next-quarter operating plans.",
    decisionAreas: ["capital-raising", "hiring"],
    supportPoints: ["Convert optimism into bounded operating rules.", "Set weekly flip checks."],
  },
  {
    slug: "is-venture-funding-recovering",
    keyword: "is venture funding recovering",
    title: "Is Venture Funding Recovering?",
    category: "climate",
    directAnswer: "Recovery is underway, but quality bar and timing discipline still matter.",
    audience: "Founders planning fundraising windows.",
    decisionAreas: ["capital-raising"],
    supportPoints: ["Raise from leverage, not urgency.", "Keep a downside process ready."],
  },
  {
    slug: "tech-funding-environment",
    keyword: "tech funding environment",
    title: "Tech Funding Environment",
    category: "climate",
    directAnswer: "Environment supports selective expansion, not blanket spend acceleration.",
    audience: "COO/CFO stakeholders balancing growth and durability.",
    decisionAreas: ["burn-discipline", "expansion-bets"],
    supportPoints: ["Approve only measurable-return expansions.", "Keep burn guardrails active."],
  },
  {
    slug: "startup-hiring-trends",
    keyword: "startup hiring trends",
    title: "Startup Hiring Trends",
    category: "climate",
    directAnswer: "Hiring conditions support targeted additions in high-leverage roles.",
    audience: "VP Engineering and product leaders setting hiring plans.",
    decisionAreas: ["hiring"],
    supportPoints: ["Prioritize reliability and revenue-linked roles.", "Avoid broad hiring waves."],
  },
  {
    slug: "should-startups-hire-engineers-right-now",
    keyword: "should startups hire engineers right now",
    title: "Should Startups Hire Engineers Right Now?",
    category: "decision",
    directAnswer: "Yes for selective, impact-linked roles; no for blanket growth hiring.",
    audience: "Founders and VP Engineering teams deciding headcount now.",
    decisionAreas: ["hiring"],
    supportPoints: ["Backfill reliability roles first.", "Require explicit payback for net-new roles."],
  },
  {
    slug: "should-startups-slow-product-development",
    keyword: "should startups slow product development",
    title: "Should Startups Slow Product Development?",
    category: "decision",
    directAnswer: "Slow long-payback bets, not core delivery tempo.",
    audience: "Product and engineering leadership teams.",
    decisionAreas: ["product-tempo"],
    supportPoints: ["Protect validated roadmap throughput.", "Stage long-cycle projects behind milestones."],
  },
  {
    slug: "should-startups-raise-capital-now",
    keyword: "should startups raise capital now",
    title: "Should Startups Raise Capital Now?",
    category: "decision",
    directAnswer: "Raise proactively if strategic optionality improves and runway use is clear.",
    audience: "CEO/CFO teams timing financing decisions.",
    decisionAreas: ["capital-raising", "burn-discipline"],
    supportPoints: ["Define use of funds before process launch.", "Avoid reactive raise timing."],
  },
  {
    slug: "when-should-startups-cut-burn",
    keyword: "when startups should cut burn",
    title: "When Should Startups Cut Burn?",
    category: "decision",
    directAnswer: "Cut burn as soon as tightness worsens and raise window weakens.",
    audience: "COO/CFO teams managing runway risk.",
    decisionAreas: ["burn-discipline"],
    supportPoints: ["Protect runway before constraint compounds.", "Tie cuts to predefined triggers."],
  },
  {
    slug: "product-strategy-during-downturn",
    keyword: "product strategy during downturn",
    title: "Product Strategy During Downturn",
    category: "decision",
    directAnswer: "Concentrate on retention/reliability and pause speculative expansions.",
    audience: "Product leadership in defensive planning cycles.",
    decisionAreas: ["product-tempo", "expansion-bets"],
    supportPoints: ["Increase proof thresholds.", "Prefer reversible scope changes."],
  },
  {
    slug: "product-strategy-during-expansion",
    keyword: "product strategy during expansion",
    title: "Product Strategy During Expansion",
    category: "decision",
    directAnswer: "Use the window for reversible growth bets while maintaining payback controls.",
    audience: "Product leaders in execution acceleration mode.",
    decisionAreas: ["product-tempo", "expansion-bets"],
    supportPoints: ["Increase experiment velocity.", "Keep stop-loss checkpoints explicit."],
  },
  {
    slug: "when-to-expand-startup-hiring",
    keyword: "when to expand startup hiring",
    title: "When to Expand Startup Hiring",
    category: "decision",
    directAnswer: "Expand in tranches once tightness stays below guardrail for multiple weekly reads.",
    audience: "Exec teams approving headcount envelope changes.",
    decisionAreas: ["hiring"],
    supportPoints: ["Use tranche-based approvals.", "Keep rollback trigger pre-approved."],
  },
  {
    slug: "startup-strategy-in-uncertain-markets",
    keyword: "startup strategy in uncertain markets",
    title: "Startup Strategy in Uncertain Markets",
    category: "decision",
    directAnswer: "Operate with explicit thresholds, staged bets, and weekly review cadence.",
    audience: "Founders/COO teams in mixed-signal environments.",
    decisionAreas: ["burn-discipline", "expansion-bets", "product-tempo"],
    supportPoints: ["Convert posture into policy.", "Avoid irreversible commitments without trigger checks."],
  },
  {
    slug: "how-macro-conditions-affect-startups",
    keyword: "how macro conditions affect startups",
    title: "How Macro Conditions Affect Startups",
    category: "explanation",
    directAnswer: "Macro affects your approval speed, financing options, and tolerance for long-payback bets.",
    audience: "Leaders onboarding teams to weekly operating posture.",
    decisionAreas: ["capital-raising", "product-tempo", "burn-discipline"],
    supportPoints: ["Translate macro into bounded rules.", "Debate thresholds, not labels."],
  },
  {
    slug: "how-interest-rates-affect-startups",
    keyword: "how interest rates affect startups",
    title: "How Interest Rates Affect Startups",
    category: "explanation",
    directAnswer: "Higher rates usually tighten capital and shorten acceptable payback windows.",
    audience: "Founders and product leaders linking rates to execution policy.",
    decisionAreas: ["capital-raising", "burn-discipline"],
    supportPoints: ["Use rate direction as pacing input.", "Adjust burn and raise timing together."],
  },
  {
    slug: "venture-funding-cycle-explained",
    keyword: "venture funding cycle explained",
    title: "Venture Funding Cycle Explained",
    category: "explanation",
    directAnswer: "Funding cycles set your financing leverage and error tolerance on spend.",
    audience: "Exec teams aligning board narrative with operating decisions.",
    decisionAreas: ["capital-raising", "burn-discipline"],
    supportPoints: ["Use cycle state to set raise timing.", "Keep downside triggers explicit."],
  },
  {
    slug: "how-macro-affects-product-strategy",
    keyword: "how macro affects product strategy",
    title: "How Macro Affects Product Strategy",
    category: "explanation",
    directAnswer: "Macro changes which roadmap bets deserve speed versus gates.",
    audience: "Product/engineering leadership teams.",
    decisionAreas: ["product-tempo", "expansion-bets"],
    supportPoints: ["Prioritize reversible bets in weak conditions.", "Scale proven bets when window improves."],
  },
  {
    slug: "how-to-brief-executives-on-market-conditions",
    keyword: "how to brief executives on market conditions",
    title: "How to Brief Executives on Market Conditions",
    category: "explanation",
    directAnswer: "Lead with what changed, what decisions change, and what flips the call.",
    audience: "Chief of Staff, COO, and leadership comms owners.",
    decisionAreas: ["burn-discipline", "hiring", "capital-raising"],
    supportPoints: ["Use concise artifact-ready summaries.", "Include citation + cadence + confidence."],
  },
];

export const findDecisionPage = (slug: string) =>
  tierOneDecisionPages.find((page) => page.slug === slug);

export const tierTwoKeywords = [
  "startup strategy in uncertain markets",
  "product strategy during downturn",
  "product strategy during expansion",
];

export const tierThreeKeywords = [
  "how macro affects product strategy",
  "how interest rates affect startups",
  "venture funding cycle explained",
];
